In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [4]:
df = pd.read_excel("../data/fashion_brands_dataset.xlsx")

In [5]:
df.head()

,Brand,Category,Country,Followers_Million,Engagement_Rate,Avg_Price_USD,Sustainability,Target_Audience,Global_Stores,Trend_Score,Collaboration_Count,Collaboration_Score
0,Nike,Sportswear,USA,27,1.90,166,High,Young Adults,3549,83,9,NaN
1,Adidas,Sportswear,Germany,60,2.63,98,Medium,Adults,4118,86,19,NaN
2,Puma,Sportswear,Germany,79,2.86,88,Medium,Young Adults,1217,75,13,NaN
3,Zara,Fast Fashion,Spain,22,1.35,46,High,Adults,681,84,12,NaN
4,H&M,Fast Fashion,Sweden,15,1.72,65,High,Adults,2386,92,6,NaN

In [6]:
df.shape

(101, 12)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brand                101 non-null    object
 1   Category             101 non-null    object
 2   Country              101 non-null    object
 3   Followers_Million    101 non-null    int64
 4   Engagement_Rate      101 non-null    float64
 5   Avg_Price_USD        101 non-null    int64
 6   Sustainability       101 non-null    object
 7   Target_Audience      101 non-null    object
 8   Global_Stores        101 non-null    int64
 9   Trend_Score          101 non-null    int64
 10  Collaboration_Count  101 non-null    int64
 11  Collaboration_Score  0 non-null      float64
dtypes: float64(2), int64(5), object(5)
memory usage: 9.6+ KB

In [8]:
df.describe()

,Followers_Million,Engagement_Rate,Avg_Price_USD,Global_Stores,Trend_Score,Collaboration_Count,Collaboration_Score
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,0.0
mean,66.108911,2.036238,290.069307,2493.386139,84.059406,14.722772,NaN
std,78.321504,0.501739,471.893468,1339.851380,8.099163,6.612290,NaN
min,3.000000,1.200000,29.000000,114.000000,70.000000,3.000000,NaN
25%,17.000000,1.640000,65.000000,1560.000000,77.000000,10.000000,NaN
50%,34.000000,1.980000,104.000000,2503.000000,83.000000,14.000000,NaN
75%,68.000000,2.460000,141.000000,3549.000000,92.000000,21.000000,NaN
max,315.000000,2.990000,1985.000000,4841.000000,98.000000,25.000000,NaN

In [9]:
df.isnull().sum()

Brand                    0
Category                 0
Country                  0
Followers_Million        0
Engagement_Rate          0
Avg_Price_USD            0
Sustainability           0
Target_Audience          0
Global_Stores            0
Trend_Score              0
Collaboration_Count      0
Collaboration_Score    101
dtype: int64